### ISSUE TITLE
How to use customized images for Icons instead of Flutter-integrated icons?

### ISSUE THREAD

**Issue by zinwalin** [55Builds/Flutter-FFNavigationBar#10]
thanks.

**Comment by Jaydub55** [comment]
Hi @zinwalin , it doesn't support it directly in the current version.  

At the moment the FFNavigationBarItem has a private method **_makeIcon** which creates a Widget which will be used as the child of the CircleAvatar element.

```
Widget _makeIcon(
    IconData iconData,
  ) {
    bool isSelected = _isItemSelected();
    return Icon(
      iconData,
      color: isSelected
          ? selectedForegroundColor ?? theme.selectedItemIconColor
          : theme.unselectedItemIconColor,
    );
  }
```

You could try modifying this to return an image (asset or network) instead of the icon, which would still be a valid child of the CircleAvatar element.
