### ISSUE TITLE
Hitbox too small

### ISSUE THREAD

**Issue by linxydmhg** [55Builds/Flutter-FFNavigationBar#14]
You have to hit exactly on the text or icon, which makes it easy to miss when clicking the NavBar item

**Comment by MathiasVandePol** [comment]
Yep, facing same issue here. Looks like only the icon area is hittable.

**Comment by crockford55** [comment]
Watch out for a new version which places the GestureDetector around a SizedBox widget which will be sized to:
* Height = theme.barHeight
* Width = MediaQuery.of(context).size.width / `number of items in navbar`

That should give you a uniform hitbox size rather than having it collapse to the size of its content.
